version: "3.3"
services:
  web:
    container_name: todo-frontend
    image: tutug:todoer
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: "50Mi"
    ports:
      - "80:80"
  app:
    container_name: todo-backend
    image: tutug/todoerapp
    deploy:
       replicas: 4
       resources:
         limits:
           cpus: "0.1"
           memory: "50Mi"
  db:
    container_name: dbserver
    image: postgres
    
