version: 0.2

env:
  variables:
    JWT_SECRET: 'jwtsecretkey'
    PORT: 3005
    API_URL: 'http://localhost:3005/api'
phases:
  install:
    commands:
      - echo install started on `date`
      - curl -sL https://rpm.nodesource.com/setup_8.x | bash -
      - yum -y install nodejs
      - npm --version 
      - node --version
      - npm install
  pre_build:
    commands:
      - npm run test:server
  build:
    command:
      - npm run build
  post_build:
    commands:
      - ls
      - echo build complated on `date`
artifacts:
  files:
    - 'src/*'
    - 'public/*'
    - 'package.json'
    - 'package-lock.json'
    - 'k8s/*'
    - 'Dockerfile'
