apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  labels:
    app: todoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: todoapp
        image: tutug/todoapp:latest
        ports:
          - containerPort: 3005
